import {
    SiJavascript, SiPython, SiTypescript, SiC, SiCplusplus, SiCss3, SiHtml5,
    SiReact, SiAngular, SiNodedotjs, SiFastapi, SiFlask, SiSpring, SiSpringboot,
    SiRedis, SiPostgresql,
    SiDocker, SiJenkins, SiKubernetes, SiLinux, SiCmake, SiGnubash, SiTekton,
    SiJira, SiGit, SiPostman, SiNpm, SiGraphql, SiGradle, SiApachemaven,
    SiVim, SiTerraform, SiTensorflow, SiWebstorm, SiSwagger, SiTailwindcss, SiNextdotjs,
    SiGooglecloud, SiNumpy, SiPandas,
    SiPytorch, SiScikitlearn, SiJupyter, SiFossa, SiSonarqube,
    SiClion, SiDatagrip, SiIntellijidea,   SiPycharm, } from 'react-icons/si';
import { FaJava, FaAws } from 'react-icons/fa';
import { VscVscodeInsiders } from "react-icons/vsc";

export const ICONS = [
    FaJava,
    SiSpring,
    SiSpringboot,
    SiIntellijidea,
    SiGradle,
    SiApachemaven,
    SiGraphql,
    SiPython,
    SiFastapi,
    SiFlask,
    SiPycharm,
    SiC,
    SiCplusplus,
    SiCmake,
    SiClion,
    SiJavascript,
    SiTypescript,
    SiCss3,
    SiHtml5,
    SiWebstorm,
    SiReact,
    SiAngular,
    SiTailwindcss,
    VscVscodeInsiders,
    SiNextdotjs,
    SiNodedotjs,
    SiNpm,
    SiPostgresql,
    SiRedis,
    SiDatagrip,
    SiPytorch,
    SiTensorflow,
    SiScikitlearn,
    SiJupyter,
    SiNumpy,
    SiPandas,
    FaAws,
    SiGooglecloud,
    SiTerraform,
    SiDocker,
    SiKubernetes,
    SiTekton,
    SiJenkins,
    SiSwagger,
    SiPostman,
    SiGit,
    SiGnubash,
    SiLinux,
    SiVim,
    SiSonarqube,
    SiFossa,
    SiJira
]